
# Gem::Specification for Www-delicious-0.2.0
# Originally generated by Echoe

--- !ruby/object:Gem::Specification 
name: www-delicious
version: !ruby/object:Gem::Version 
  version: 0.2.0
platform: ruby
authors: 
- Simone Carletti
autorequire: 
bindir: bin

date: 2008-08-11 00:00:00 +02:00
default_executable: 
dependencies: 
- !ruby/object:Gem::Dependency 
  name: rake
  type: :development
  version_requirement: 
  version_requirements: !ruby/object:Gem::Requirement 
    requirements: 
    - - ">="
      - !ruby/object:Gem::Version 
        version: "0.8"
    version: 
- !ruby/object:Gem::Dependency 
  name: echoe
  type: :development
  version_requirement: 
  version_requirements: !ruby/object:Gem::Requirement 
    requirements: 
    - - ">="
      - !ruby/object:Gem::Version 
        version: "3"
    version: 
- !ruby/object:Gem::Dependency 
  name: mocha
  type: :development
  version_requirement: 
  version_requirements: !ruby/object:Gem::Requirement 
    requirements: 
    - - ">="
      - !ruby/object:Gem::Version 
        version: "0.9"
    version: 
description: WWW::Delicious is a del.icio.us API client implemented in Ruby.     It provides access to all available del.icio.us API queries     and returns the original XML response as a friendly Ruby object.
email: weppos@weppos.net
executables: []

extensions: []

extra_rdoc_files: 
- CHANGELOG.rdoc
- lib/www/delicious/bundle.rb
- lib/www/delicious/element.rb
- lib/www/delicious/errors.rb
- lib/www/delicious/post.rb
- lib/www/delicious/tag.rb
- lib/www/delicious/version.rb
- lib/www/delicious.rb
- README.rdoc
files: 
- CHANGELOG.rdoc
- lib/www/delicious/bundle.rb
- lib/www/delicious/element.rb
- lib/www/delicious/errors.rb
- lib/www/delicious/post.rb
- lib/www/delicious/tag.rb
- lib/www/delicious/version.rb
- lib/www/delicious.rb
- MIT-LICENSE.rdoc
- Rakefile
- README.rdoc
- setup.rb
- test/fixtures/net_response_invalid_account.yml
- test/fixtures/net_response_success.yml
- test/helper.rb
- test/test_all.rb
- test/test_offline.rb
- test/test_online.rb
- test/testcases/element/bundle.xml
- test/testcases/element/invalid_root.xml
- test/testcases/element/post.xml
- test/testcases/element/post_unshared.xml
- test/testcases/element/tag.xml
- test/testcases/response/bundles_all.xml
- test/testcases/response/bundles_all_empty.xml
- test/testcases/response/bundles_delete.xml
- test/testcases/response/bundles_set.xml
- test/testcases/response/bundles_set_error.xml
- test/testcases/response/posts_add.xml
- test/testcases/response/posts_all.xml
- test/testcases/response/posts_dates.xml
- test/testcases/response/posts_dates_with_tag.xml
- test/testcases/response/posts_delete.xml
- test/testcases/response/posts_get.xml
- test/testcases/response/posts_get_with_tag.xml
- test/testcases/response/posts_recent.xml
- test/testcases/response/posts_recent_with_tag.xml
- test/testcases/response/tags_get.xml
- test/testcases/response/tags_get_empty.xml
- test/testcases/response/tags_rename.xml
- test/testcases/response/update.delicious1.xml
- test/testcases/response/update.xml
- test/unit/bundle_test.rb
- test/unit/delicious_test.rb
- test/unit/online/online_test.rb
- test/unit/post_test.rb
- test/unit/tag_test.rb
- TODO
- Manifest
- www-delicious.gemspec
has_rdoc: true
homepage: http://code.simonecarletti.com/www-delicious
post_install_message: 
rdoc_options: 
- --line-numbers
- --inline-source
- --title
- Www-delicious
- --main
- README.rdoc
require_paths: 
- lib
required_ruby_version: !ruby/object:Gem::Requirement 
  requirements: 
  - - ">="
    - !ruby/object:Gem::Version 
      version: "0"
  version: 
required_rubygems_version: !ruby/object:Gem::Requirement 
  requirements: 
  - - "="
    - !ruby/object:Gem::Version 
      version: "1.2"
  version: 
requirements: []

rubyforge_project: www-delicious
rubygems_version: 1.2.0
specification_version: 2
summary: Ruby client for del.icio.us API.
test_files: 
- test/test_all.rb
